/* 
* Generated by
* 
*      _____ _          __  __      _     _
*     / ____| |        / _|/ _|    | |   | |
*    | (___ | | ____ _| |_| |_ ___ | | __| | ___ _ __
*     \___ \| |/ / _` |  _|  _/ _ \| |/ _` |/ _ \ '__|
*     ____) |   < (_| | | | || (_) | | (_| |  __/ |
*    |_____/|_|\_\__,_|_| |_| \___/|_|\__,_|\___|_|
*
* The code generator that works in many programming languages
*
*			https://www.skaffolder.com
*
*
* You can generate the code from the command-line
*       https://npmjs.com/package/skaffolder-cli
*
*       npm install -g skaffodler-cli
*
*   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *
*
* To remove this comment please upgrade your plan here: 
*      https://app.skaffolder.com/#!/upgrade
*
* Or get up to 70% discount sharing your unique link:
*       https://app.skaffolder.com/#!/register?friend=5dbfae239ef7a1181f8e04d2
*
* You will get 10% discount for each one of your friends
* 
*/
// Dependencies
import React, { Component } from "react";
import { Fragment } from "react";
import { Route, Switch } from "react-router";
import { PrivateRoute } from "./security/PrivateRoute";

// Material UI
import Paper from "@material-ui/core/Paper";

/* START MY VIEWS IMPORT */

import UserEdit from "./pages/UserEdit";
import UserList from "./pages/UserList";
import BillEdit from "./pages/BillEdit";
import BillList from "./pages/BillList";
import CostomerEdit from "./pages/CostomerEdit";
import CostomerList from "./pages/CostomerList";
import EmployessEdit from "./pages/EmployessEdit";
import EmployessList from "./pages/EmployessList";
import RoomEdit from "./pages/RoomEdit";
import RoomList from "./pages/RoomList";
import ServiseEdit from "./pages/ServiseEdit";
import ServiseList from "./pages/ServiseList";

/* END MY VIEWS IMPORT */

// CUSTOM VIEWS
import Login from "./pages/Login";
import Home from "./pages/Home";
import Profile from "./pages/Profile";
import UserEdit from "./pages/UserEdit";
import UserList from "./pages/UserList";

class Routes extends Component {
  render() {
    return (
      <Switch>
        <Fragment>
          <Paper>
            <div className="main-cointainer">
              <Route exact path="/login" component={Login} />
              <PrivateRoute exact path="/" component={Home} />
              <PrivateRoute exact path="/profile" component={Profile} />
              <PrivateRoute exact path="/users/:id" component={UserEdit} roles={["ADMIN"]}/>
              <PrivateRoute exact path="/users" component={UserList} roles={["ADMIN"]}/>
              
              {/* CUSTOM VIEWS */}

              <PrivateRoute exact path="/home" component={Home} />

              {/* START MY VIEWS */}

              <PrivateRoute exact path="/users/:id" component={ UserEdit }  />
              <PrivateRoute exact path="/users" component={ UserList }  />
              <PrivateRoute exact path="/bills/:id" component={ BillEdit }  />
              <PrivateRoute exact path="/bills" component={ BillList }  />
              <PrivateRoute exact path="/costomers/:id" component={ CostomerEdit }  />
              <PrivateRoute exact path="/costomers" component={ CostomerList }  />
              <PrivateRoute exact path="/employesses/:id" component={ EmployessEdit }  />
              <PrivateRoute exact path="/employesses" component={ EmployessList }  />
              <PrivateRoute exact path="/rooms/:id" component={ RoomEdit }  />
              <PrivateRoute exact path="/rooms" component={ RoomList }  />
              <PrivateRoute exact path="/servises/:id" component={ ServiseEdit }  />
              <PrivateRoute exact path="/servises" component={ ServiseList }  />

             {/* END MY VIEWS */}

            </div>
          </Paper>
        </Fragment>
      </Switch>
    );
  }
}

export default Routes;