/* 
* Generated by
* 
*      _____ _          __  __      _     _
*     / ____| |        / _|/ _|    | |   | |
*    | (___ | | ____ _| |_| |_ ___ | | __| | ___ _ __
*     \___ \| |/ / _` |  _|  _/ _ \| |/ _` |/ _ \ '__|
*     ____) |   < (_| | | | || (_) | | (_| |  __/ |
*    |_____/|_|\_\__,_|_| |_| \___/|_|\__,_|\___|_|
*
* The code generator that works in many programming languages
*
*			https://www.skaffolder.com
*
*
* You can generate the code from the command-line
*       https://npmjs.com/package/skaffolder-cli
*
*       npm install -g skaffodler-cli
*
*   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *
*
* To remove this comment please upgrade your plan here: 
*      https://app.skaffolder.com/#!/upgrade
*
* Or get up to 70% discount sharing your unique link:
*       https://app.skaffolder.com/#!/register?friend=5dbfae239ef7a1181f8e04d2
*
* You will get 10% discount for each one of your friends
* 
*/
// Dependencies
import React, { Component } from "react";
import { Link } from "react-router-dom";
import Utils from "../utils/utils";

// Redux
import PropTypes from "prop-types";
import { bindActionCreators } from "redux";
import { connect } from "react-redux";

// Material UI
import TextField from "@material-ui/core/TextField";
import Button from "@material-ui/core/Button";
import Select from "@material-ui/core/Select";
import MenuItem from "@material-ui/core/MenuItem";
import InputLabel from "@material-ui/core/InputLabel";
import FormControl from "@material-ui/core/FormControl";

// Custom Actions


// START IMPORT ACTIONS
import EmployessActions from "../redux/actions/EmployessActions";

// END IMPORT ACTIONS

/** APIs

* actionsEmployess.create
*	@description CRUD ACTION create
*	@param employess obj - Object to insert
*
* actionsEmployess.get
*	@description CRUD ACTION get
*	@param ObjectId id - Id employess
*	@returns employess
*
* actionsUser.list
*	@description CRUD ACTION list
*
* actionsEmployess.update
*	@description CRUD ACTION update
*	@param ObjectId id - Id employess
*	@returns employess
*

**/

class EmployessEdit extends Component {
  // Init employess
  constructor(props) {
    super(props);
    this.state = {
      employess: {}
    };
  }

  // Load data on start
  componentDidMount() {
    if (this.props.match.params.id !== "new") {
      this.props.actionsEmployess.loadEmployess(this.props.match.params.id);
    }
    
    this.props.actionsRoom.loadRoomList();
    this.props.actionsBill.loadBillList();
  }

  // Insert props employess in state
  componentWillReceiveProps(props) {
    this.setState(...this.state, {
      employess: props.employess
    });
  }

  // Save data
  save(event) {
    event.preventDefault();
    if (this.state.employess._id) {
      this.props.actionsEmployess.saveEmployess(this.state.employess).then(data => {
        this.props.history.push("/employesses/");
      });
    } else {
      this.props.actionsEmployess.createEmployess(this.state.employess).then(data => {
        this.props.history.push("/employesses/");
      });
    }
  }

  // Show content
  render() {
    return (
      <div>
        <h1>Employess Edit</h1>
        <form className="myForm" onSubmit={this.save.bind(this)}>

          
          <TextField
            id="disc"
            label="Disc"
            value={this.state.employess.disc || ""}
            onChange={Utils.handleChange.bind(this, "employess")}
            margin="normal"
            fullWidth
          />
          
          
          <TextField
            id="gender"
            label="Gender"
            value={this.state.employess.gender || ""}
            onChange={Utils.handleChange.bind(this, "employess")}
            margin="normal"
            fullWidth
          />
          
          
          <TextField
            id="name"
            label="Name"
            value={this.state.employess.name || ""}
            onChange={Utils.handleChange.bind(this, "employess")}
            margin="normal"
            fullWidth
          />
          
          
          <TextField
            id="position"
            label="Position"
            value={this.state.employess.position || ""}
            onChange={Utils.handleChange.bind(this, "employess")}
            margin="normal"
            fullWidth
          />
          
          
          <TextField
            id="salary"
            label="Salary"
            value={this.state.employess.salary || ""}
            onChange={Utils.handleChange.bind(this, "employess")}
            margin="normal"
            fullWidth
          />
          
          {/* RELATIONS */}

          <h2 className="mb-20">Relations</h2>
          
          {/* Relation 1:m employessid with room */}
          
          <FormControl fullWidth className="mb-20">
            <InputLabel shrink htmlFor="employessid">
              Employessid
            </InputLabel>
            <Select
              value={this.state.employess.employessid || ""}
              onChange={Utils.handleChangeSelect.bind(this, "employess")}
              inputProps={{
                id: "employessid",
                name: "employessid"
              }}
              fullWidth
            >
              <MenuItem value="">
                <em>None</em>
              </MenuItem>
              {this.props.listRoom && this.props.listRoom.map(row => (
                <MenuItem value={row._id} key={row._id}>
                  {row._id}
                </MenuItem>
              ))}
            </Select>
          </FormControl>
          
          
          {/* Relation 1:m employessid with bill */}
          
          <FormControl fullWidth className="mb-20">
            <InputLabel shrink htmlFor="employessid">
              Employessid
            </InputLabel>
            <Select
              value={this.state.employess.employessid || ""}
              onChange={Utils.handleChangeSelect.bind(this, "employess")}
              inputProps={{
                id: "employessid",
                name: "employessid"
              }}
              fullWidth
            >
              <MenuItem value="">
                <em>None</em>
              </MenuItem>
              {this.props.listBill && this.props.listBill.map(row => (
                <MenuItem value={row._id} key={row._id}>
                  {row._id}
                </MenuItem>
              ))}
            </Select>
          </FormControl>
          
          
          {/* Footer */}
          <div className="footer-card">
            <Link to="/employesses/">Back to list</Link>

            <Button type="submit" variant="contained" color="primary">
              Save
            </Button>
          </div>
        </form>
      </div>
    );
  }
}

// Store actions
const mapDispatchToProps = function(dispatch) {
  return { 
    actionsEmployess: bindActionCreators(EmployessActions, dispatch),
  };
};

// Validate types
EmployessEdit.propTypes = { 
  actionsEmployess: PropTypes.object.isRequired,
};

// Get props from state
function mapStateToProps(state, ownProps) {
  return {
    employess: state.EmployessEditReducer.employess,
    listRoom: state.EmployessEditReducer.listRoom,
    listBill: state.EmployessEditReducer.listBill
  };
}

export default connect(
  mapStateToProps,
  mapDispatchToProps
)(EmployessEdit);
