/* 
* Generated by
* 
*      _____ _          __  __      _     _
*     / ____| |        / _|/ _|    | |   | |
*    | (___ | | ____ _| |_| |_ ___ | | __| | ___ _ __
*     \___ \| |/ / _` |  _|  _/ _ \| |/ _` |/ _ \ '__|
*     ____) |   < (_| | | | || (_) | | (_| |  __/ |
*    |_____/|_|\_\__,_|_| |_| \___/|_|\__,_|\___|_|
*
* The code generator that works in many programming languages
*
*			https://www.skaffolder.com
*
*
* You can generate the code from the command-line
*       https://npmjs.com/package/skaffolder-cli
*
*       npm install -g skaffodler-cli
*
*   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *
*
* To remove this comment please upgrade your plan here: 
*      https://app.skaffolder.com/#!/upgrade
*
* Or get up to 70% discount sharing your unique link:
*       https://app.skaffolder.com/#!/register?friend=5dbfae239ef7a1181f8e04d2
*
* You will get 10% discount for each one of your friends
* 
*/
// Dependencies
import React, { Component } from "react";
import { Link } from "react-router-dom";
import Utils from "../utils/utils";

// Redux
import PropTypes from "prop-types";
import { bindActionCreators } from "redux";
import { connect } from "react-redux";

// Material UI
import TextField from "@material-ui/core/TextField";
import Button from "@material-ui/core/Button";
import Select from "@material-ui/core/Select";
import MenuItem from "@material-ui/core/MenuItem";
import InputLabel from "@material-ui/core/InputLabel";
import FormControl from "@material-ui/core/FormControl";

// Custom Actions


// START IMPORT ACTIONS
import RoomActions from "../redux/actions/RoomActions";
import EmployessActions from "../redux/actions/EmployessActions";
import ServiseActions from "../redux/actions/ServiseActions";
import CostomerActions from "../redux/actions/CostomerActions";
import BillActions from "../redux/actions/BillActions";

// END IMPORT ACTIONS

/** APIs

* actionsRoom.create
*	@description CRUD ACTION create
*	@param room obj - Object to insert
*
* actionsEmployess.findByemployessid
*	@description CRUD ACTION findByemployessid
*	@param Objectid key - Id della risorsa employessid da cercare
*
* actionsServise.findByidservise
*	@description CRUD ACTION findByidservise
*	@param Objectid key - Id della risorsa idservise da cercare
*
* actionsRoom.get
*	@description CRUD ACTION get
*	@param ObjectId id - Id room
*	@returns room
*
* actionsCostomer.list
*	@description CRUD ACTION list
*	@returns ARRAY OF costomer
*
* actionsBill.list
*	@description CRUD ACTION list
*	@returns ARRAY OF bill
*
* actionsRoom.update
*	@description CRUD ACTION update
*	@param ObjectId id - Id room
*	@returns room
*

**/

class RoomEdit extends Component {
  // Init room
  constructor(props) {
    super(props);
    this.state = {
      room: {}
    };
  }

  // Load data on start
  componentDidMount() {
    if (this.props.match.params.id !== "new") {
      this.props.actionsRoom.loadRoom(this.props.match.params.id);
      this.props.actionsEmployess.findByemployessid(this.props.match.params.id);
      this.props.actionsServise.findByidservise(this.props.match.params.id);
    }
    
    this.props.actionsCostomer.loadCostomerList();
    this.props.actionsBill.loadBillList();
  }

  // Insert props room in state
  componentWillReceiveProps(props) {
    this.setState(...this.state, {
      room: props.room
    });
  }

  // Save data
  save(event) {
    event.preventDefault();
    if (this.state.room._id) {
      this.props.actionsRoom.saveRoom(this.state.room).then(data => {
        this.props.history.push("/rooms/");
      });
    } else {
      this.props.actionsRoom.createRoom(this.state.room).then(data => {
        this.props.history.push("/rooms/");
      });
    }
  }

  // Show content
  render() {
    return (
      <div>
        <h1>Room Edit</h1>
        <form className="myForm" onSubmit={this.save.bind(this)}>

          
          <TextField
            id="employessid"
            label="Employessid"
            value={this.state.room.employessid || ""}
            onChange={Utils.handleChange.bind(this, "room")}
            type="number"
            type="decimal"
            margin="normal"
            fullWidth
          />
          
          
          <TextField
            id="idservise"
            label="Idservise"
            value={this.state.room.idservise || ""}
            onChange={Utils.handleChange.bind(this, "room")}
            type="number"
            type="decimal"
            margin="normal"
            fullWidth
          />
          
          
          <TextField
            id="note"
            label="Note"
            value={this.state.room.note || ""}
            onChange={Utils.handleChange.bind(this, "room")}
            margin="normal"
            fullWidth
          />
          
          
          <TextField
            id="roomname"
            label="Roomname"
            value={this.state.room.roomname || ""}
            onChange={Utils.handleChange.bind(this, "room")}
            margin="normal"
            fullWidth
          />
          
          
          <TextField
            id="roomstauts"
            label="Roomstauts"
            value={this.state.room.roomstauts || ""}
            onChange={Utils.handleChange.bind(this, "room")}
            margin="normal"
            fullWidth
          />
          
          
          <TextField
            id="roomtype"
            label="Roomtype"
            value={this.state.room.roomtype || ""}
            onChange={Utils.handleChange.bind(this, "room")}
            margin="normal"
            fullWidth
          />
          
          
          <TextField
            id="salary"
            label="Salary"
            value={this.state.room.salary || ""}
            onChange={Utils.handleChange.bind(this, "room")}
            margin="normal"
            fullWidth
          />
          
          {/* RELATIONS */}

          <h2 className="mb-20">Relations</h2>
          
          {/* Relation 1:m coderoom with costomer */}
          
          <FormControl fullWidth className="mb-20">
            <InputLabel shrink htmlFor="coderoom">
              Coderoom
            </InputLabel>
            <Select
              value={this.state.room.coderoom || ""}
              onChange={Utils.handleChangeSelect.bind(this, "room")}
              inputProps={{
                id: "coderoom",
                name: "coderoom"
              }}
              fullWidth
            >
              <MenuItem value="">
                <em>None</em>
              </MenuItem>
              {this.props.listCostomer && this.props.listCostomer.map(row => (
                <MenuItem value={row._id} key={row._id}>
                  {row._id}
                </MenuItem>
              ))}
            </Select>
          </FormControl>
          
          
          {/* Relation 1:m roomid with bill */}
          
          <FormControl fullWidth className="mb-20">
            <InputLabel shrink htmlFor="roomid">
              Roomid
            </InputLabel>
            <Select
              value={this.state.room.roomid || ""}
              onChange={Utils.handleChangeSelect.bind(this, "room")}
              inputProps={{
                id: "roomid",
                name: "roomid"
              }}
              fullWidth
            >
              <MenuItem value="">
                <em>None</em>
              </MenuItem>
              {this.props.listBill && this.props.listBill.map(row => (
                <MenuItem value={row._id} key={row._id}>
                  {row._id}
                </MenuItem>
              ))}
            </Select>
          </FormControl>
          
          
          {/* EXTERNAL RELATIONS */}
          
          {/* External relation with employess */}
          
          <h3>Employess</h3>
          {(!this.props.listEmployess || this.props.listEmployess.length === 0) && 
            <div>No Employess associated</div>
          }
          {this.props.listEmployess &&
            this.props.listEmployess.map((item, i) => {
              return (
                <Link to={"/employesss/" + item._id} key={item._id}>
                  {item._id}
                </Link>
              );
            })}

          
          {/* External relation with servise */}
          
          <h3>Servise</h3>
          {(!this.props.listServise || this.props.listServise.length === 0) && 
            <div>No Servise associated</div>
          }
          {this.props.listServise &&
            this.props.listServise.map((item, i) => {
              return (
                <Link to={"/servises/" + item._id} key={item._id}>
                  {item._id}
                </Link>
              );
            })}

          
          {/* Footer */}
          <div className="footer-card">
            <Link to="/rooms/">Back to list</Link>

            <Button type="submit" variant="contained" color="primary">
              Save
            </Button>
          </div>
        </form>
      </div>
    );
  }
}

// Store actions
const mapDispatchToProps = function(dispatch) {
  return { 
    actionsRoom: bindActionCreators(RoomActions, dispatch),
    actionsEmployess: bindActionCreators(EmployessActions, dispatch),
    actionsServise: bindActionCreators(ServiseActions, dispatch),
    actionsCostomer: bindActionCreators(CostomerActions, dispatch),
    actionsBill: bindActionCreators(BillActions, dispatch),
  };
};

// Validate types
RoomEdit.propTypes = { 
  actionsRoom: PropTypes.object.isRequired,
  actionsEmployess: PropTypes.object.isRequired,
  actionsServise: PropTypes.object.isRequired,
  actionsCostomer: PropTypes.object.isRequired,
  actionsBill: PropTypes.object.isRequired,
};

// Get props from state
function mapStateToProps(state, ownProps) {
  return {
    room: state.RoomEditReducer.room,
    listCostomer: state.RoomEditReducer.listCostomer,
    listBill: state.RoomEditReducer.listBill,
    listEmployess: state.RoomEditReducer.listEmployess,
    listServise: state.RoomEditReducer.listServise
  };
}

export default connect(
  mapStateToProps,
  mapDispatchToProps
)(RoomEdit);
