/* 
* Generated by
* 
*      _____ _          __  __      _     _
*     / ____| |        / _|/ _|    | |   | |
*    | (___ | | ____ _| |_| |_ ___ | | __| | ___ _ __
*     \___ \| |/ / _` |  _|  _/ _ \| |/ _` |/ _ \ '__|
*     ____) |   < (_| | | | || (_) | | (_| |  __/ |
*    |_____/|_|\_\__,_|_| |_| \___/|_|\__,_|\___|_|
*
* The code generator that works in many programming languages
*
*			https://www.skaffolder.com
*
*
* You can generate the code from the command-line
*       https://npmjs.com/package/skaffolder-cli
*
*       npm install -g skaffodler-cli
*
*   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *
*
* To remove this comment please upgrade your plan here: 
*      https://app.skaffolder.com/#!/upgrade
*
* Or get up to 70% discount sharing your unique link:
*       https://app.skaffolder.com/#!/register?friend=5dbfae239ef7a1181f8e04d2
*
* You will get 10% discount for each one of your friends
* 
*/
// Dependencies
import React, { Component } from "react";
import { Link } from "react-router-dom";
import DialogDelete from "../components/DialogDelete";

// Redux
import PropTypes from "prop-types";
import { bindActionCreators } from "redux";
import { connect } from "react-redux";

// Material UI
import Button from "@material-ui/core/Button";
// import Table from "@material-ui/core/Table";
// import TableBody from "@material-ui/core/TableBody";
// import TableCell from "@material-ui/core/TableCell";
// import TableHead from "@material-ui/core/TableHead";
// import TableRow from "@material-ui/core/TableRow";

// Table
import EnhancedTable from "../components/EnhancedTable";

// Custom Actions


// START IMPORT ACTIONS
import RoomActions from "../redux/actions/RoomActions";

// END IMPORT ACTIONS

/** APIs

* actionsRoom.delete
*	@description CRUD ACTION delete
*	@param ObjectId id - Id room
*
* actionsRoom.list
*	@description CRUD ACTION list
*	@returns ARRAY OF room
*

**/


class RoomList extends Component {
  // Init component
  constructor(props) {
    super(props);
    this.state = {
      openDialogDelete: false
    };
  }

  // Load data on start
  componentWillMount() {
    this.props.actionsRoom.loadRoomList();
  }

  // Delete data
  delete(id) {
    this.setState({ openDialogDelete: true, idDelete: id });
  }

  closeDialogDelete() {
    this.setState({ openDialogDelete: false, idDelete: null });
  }

  confirmDialogDelete(id) {
    this.props.actionsRoom.deleteRoom(this.state.idDelete).then(data => {
      this.props.actionsRoom.loadRoomList();
      this.setState({ openDialogDelete: false, idDelete: null });
    });
  }

  // Show content
  render() {
    const columns = [ 
      {
        id: "employessid",
        type: "integer",
        label: "Employessid"
      }, 
      {
        id: "idservise",
        type: "integer",
        label: "Idservise"
      }, 
      {
        id: "note",
        type: "string",
        label: "Note"
      }, 
      {
        id: "roomname",
        type: "string",
        label: "Roomname"
      }, 
      {
        id: "roomstauts",
        type: "string",
        label: "Roomstauts"
      }, 
      {
        id: "roomtype",
        type: "string",
        label: "Roomtype"
      }, 
      {
        id: "salary",
        type: "decimal",
        label: "Salary"
      },
    ];
    const link = "/rooms/";

    return (
      <div>
        <h1>Room List</h1>

        <EnhancedTable
          data={this.props.list}
          columns={columns}
          link={link}
          onDelete={this.delete.bind(this)}
        />

        <DialogDelete
          open={this.state.openDialogDelete}
          onClose={this.closeDialogDelete.bind(this)}
          onConfirm={this.confirmDialogDelete.bind(this)}
        />

        {/*
        <Table>
          <TableHead>
            <TableRow>
              <TableCell>ID</TableCell>
              <TableCell align="right">Employessid</TableCell>
              <TableCell align="right">Idservise</TableCell>
              <TableCell align="right">Note</TableCell>
              <TableCell align="right">Roomname</TableCell>
              <TableCell align="right">Roomstauts</TableCell>
              <TableCell align="right">Roomtype</TableCell>
              <TableCell align="right">Salary</TableCell>
            </TableRow>
          </TableHead>
          <TableBody>
            {this.props.list.map(row => (
              <TableRow key={row._id}>
                <TableCell component="th" scope="row">
                  <Link to={"/rooms/" + row._id} key={row._id}>
                    {row._id}
                  </Link>
                </TableCell>
                <TableCell align="right">{ row.employessid }</TableCell>
                <TableCell align="right">{ row.idservise }</TableCell>
                <TableCell align="right">{ row.note }</TableCell>
                <TableCell align="right">{ row.roomname }</TableCell>
                <TableCell align="right">{ row.roomstauts }</TableCell>
                <TableCell align="right">{ row.roomtype }</TableCell>
                <TableCell align="right">{ row.salary }</TableCell>
              </TableRow>
            ))}
          </TableBody>
        </Table>
        */}

        <div className="footer-card">
          <Link to="/rooms/new">
            <Button variant="contained" color="primary">
              Add
            </Button>
          </Link>
        </div>
      </div>
    );
  }
}

// Store actions
const mapDispatchToProps = function(dispatch) {
  return { 
    actionsRoom: bindActionCreators(RoomActions, dispatch),
  };
};

// Validate types
RoomList.propTypes = { 
  actionsRoom: PropTypes.object.isRequired,
};

// Get props from state
function mapStateToProps(state, ownProps) {
  return {
    list: state.RoomListReducer.listRoom
  };
}

export default connect(
  mapStateToProps,
  mapDispatchToProps
)(RoomList);
