/* 
* Generated by
* 
*      _____ _          __  __      _     _
*     / ____| |        / _|/ _|    | |   | |
*    | (___ | | ____ _| |_| |_ ___ | | __| | ___ _ __
*     \___ \| |/ / _` |  _|  _/ _ \| |/ _` |/ _ \ '__|
*     ____) |   < (_| | | | || (_) | | (_| |  __/ |
*    |_____/|_|\_\__,_|_| |_| \___/|_|\__,_|\___|_|
*
* The code generator that works in many programming languages
*
*			https://www.skaffolder.com
*
*
* You can generate the code from the command-line
*       https://npmjs.com/package/skaffolder-cli
*
*       npm install -g skaffodler-cli
*
*   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *
*
* To remove this comment please upgrade your plan here: 
*      https://app.skaffolder.com/#!/upgrade
*
* Or get up to 70% discount sharing your unique link:
*       https://app.skaffolder.com/#!/register?friend=5dbfae239ef7a1181f8e04d2
*
* You will get 10% discount for each one of your friends
* 
*/
import { combineReducers } from "redux";

// START IMPORT REDUCERS
import HomeReducer from "./HomeReducer";
import UserEditReducer from "./UserEditReducer";
import UserListReducer from "./UserListReducer";
import BillEditReducer from "./BillEditReducer";
import BillListReducer from "./BillListReducer";
import CostomerEditReducer from "./CostomerEditReducer";
import CostomerListReducer from "./CostomerListReducer";
import EmployessEditReducer from "./EmployessEditReducer";
import EmployessListReducer from "./EmployessListReducer";
import RoomEditReducer from "./RoomEditReducer";
import RoomListReducer from "./RoomListReducer";
import ServiseEditReducer from "./ServiseEditReducer";
import ServiseListReducer from "./ServiseListReducer";

// END IMPORT REDUCERS


// CUSTOM REDUCERS
import LoginReducer from "./LoginReducer";
import ProfileReducer from "./ProfileReducer";
import UserEditReducer from "./UserEditReducer";
import UserListReducer from "./UserListReducer";

const rootReducer = combineReducers({
  
  // INSERT HERE YOUR CUSTOM REDUCERS
  LoginReducer,
  ProfileReducer,
  UserEditReducer,
  UserListReducer,

  // START COMBINE REDUCERS
	HomeReducer,
	UserEditReducer,
	UserListReducer,
	BillEditReducer,
	BillListReducer,
	CostomerEditReducer,
	CostomerListReducer,
	EmployessEditReducer,
	EmployessListReducer,
	RoomEditReducer,
	RoomListReducer,
	ServiseEditReducer,
	ServiseListReducer,
 // END COMBINE REDUCERS

});

export default rootReducer;
