/* 
* Generated by
* 
*      _____ _          __  __      _     _
*     / ____| |        / _|/ _|    | |   | |
*    | (___ | | ____ _| |_| |_ ___ | | __| | ___ _ __
*     \___ \| |/ / _` |  _|  _/ _ \| |/ _` |/ _ \ '__|
*     ____) |   < (_| | | | || (_) | | (_| |  __/ |
*    |_____/|_|\_\__,_|_| |_| \___/|_|\__,_|\___|_|
*
* The code generator that works in many programming languages
*
*			https://www.skaffolder.com
*
*
* You can generate the code from the command-line
*       https://npmjs.com/package/skaffolder-cli
*
*       npm install -g skaffodler-cli
*
*   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *
*
* To remove this comment please upgrade your plan here: 
*      https://app.skaffolder.com/#!/upgrade
*
* Or get up to 70% discount sharing your unique link:
*       https://app.skaffolder.com/#!/register?friend=5dbfae239ef7a1181f8e04d2
*
* You will get 10% discount for each one of your friends
* 
*/

// INSERT HERE YOUR CUSTOM CONSTANTS




// START CRUD CONSTANTS

// USER
export const CHANGEPASSWORD_USER_SUCCESS = "CHANGEPASSWORD_USER_SUCCESS";
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const LIST_USER_SUCCESS = "LIST_USER_SUCCESS";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";

// BILL
export const CREATE_BILL_SUCCESS = "CREATE_BILL_SUCCESS";
export const DELETE_BILL_SUCCESS = "DELETE_BILL_SUCCESS";
export const FINDBYDATE_BILL_SUCCESS = "FINDBYDATE_BILL_SUCCESS";
export const GET_BILL_SUCCESS = "GET_BILL_SUCCESS";
export const LIST_BILL_SUCCESS = "LIST_BILL_SUCCESS";
export const UPDATE_BILL_SUCCESS = "UPDATE_BILL_SUCCESS";

// COSTOMER
export const CREATE_COSTOMER_SUCCESS = "CREATE_COSTOMER_SUCCESS";
export const DELETE_COSTOMER_SUCCESS = "DELETE_COSTOMER_SUCCESS";
export const FINDBYNAMCOSTOMER_COSTOMER_SUCCESS = "FINDBYNAMCOSTOMER_COSTOMER_SUCCESS";
export const GET_COSTOMER_SUCCESS = "GET_COSTOMER_SUCCESS";
export const LIST_COSTOMER_SUCCESS = "LIST_COSTOMER_SUCCESS";
export const UPDATE_COSTOMER_SUCCESS = "UPDATE_COSTOMER_SUCCESS";

// EMPLOYESS
export const CREATE_EMPLOYESS_SUCCESS = "CREATE_EMPLOYESS_SUCCESS";
export const DELETE_EMPLOYESS_SUCCESS = "DELETE_EMPLOYESS_SUCCESS";
export const FINDBYEMID_EMPLOYESS_SUCCESS = "FINDBYEMID_EMPLOYESS_SUCCESS";
export const FINDBYEMPLOYESSID_EMPLOYESS_SUCCESS = "FINDBYEMPLOYESSID_EMPLOYESS_SUCCESS";
export const FINDBYNAME_EMPLOYESS_SUCCESS = "FINDBYNAME_EMPLOYESS_SUCCESS";
export const GET_EMPLOYESS_SUCCESS = "GET_EMPLOYESS_SUCCESS";
export const LIST_EMPLOYESS_SUCCESS = "LIST_EMPLOYESS_SUCCESS";
export const UPDATE_EMPLOYESS_SUCCESS = "UPDATE_EMPLOYESS_SUCCESS";

// ROOM
export const CREATE_ROOM_SUCCESS = "CREATE_ROOM_SUCCESS";
export const DELETE_ROOM_SUCCESS = "DELETE_ROOM_SUCCESS";
export const FINDBYCODEROOM_ROOM_SUCCESS = "FINDBYCODEROOM_ROOM_SUCCESS";
export const FINDBYROOMID_ROOM_SUCCESS = "FINDBYROOMID_ROOM_SUCCESS";
export const FINDBYROOMNAME_ROOM_SUCCESS = "FINDBYROOMNAME_ROOM_SUCCESS";
export const GET_ROOM_SUCCESS = "GET_ROOM_SUCCESS";
export const LIST_ROOM_SUCCESS = "LIST_ROOM_SUCCESS";
export const UPDATE_ROOM_SUCCESS = "UPDATE_ROOM_SUCCESS";

// SERVISE
export const CREATE_SERVISE_SUCCESS = "CREATE_SERVISE_SUCCESS";
export const DELETE_SERVISE_SUCCESS = "DELETE_SERVISE_SUCCESS";
export const FINDBYIDSERVISE_SERVISE_SUCCESS = "FINDBYIDSERVISE_SERVISE_SUCCESS";
export const GET_SERVISE_SUCCESS = "GET_SERVISE_SUCCESS";
export const LIST_SERVISE_SUCCESS = "LIST_SERVISE_SUCCESS";
export const UPDATE_SERVISE_SUCCESS = "UPDATE_SERVISE_SUCCESS";

// END CRUD CONSTANTS

// USER
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS";
export const CHANGE_PASSWORD_ADMIN_SUCCESS = "CHANGE_PASSWORD_ADMIN_SUCCESS";
