/* 
* Generated by
* 
*      _____ _          __  __      _     _
*     / ____| |        / _|/ _|    | |   | |
*    | (___ | | ____ _| |_| |_ ___ | | __| | ___ _ __
*     \___ \| |/ / _` |  _|  _/ _ \| |/ _` |/ _ \ '__|
*     ____) |   < (_| | | | || (_) | | (_| |  __/ |
*    |_____/|_|\_\__,_|_| |_| \___/|_|\__,_|\___|_|
*
* The code generator that works in many programming languages
*
*			https://www.skaffolder.com
*
*
* You can generate the code from the command-line
*       https://npmjs.com/package/skaffolder-cli
*
*       npm install -g skaffodler-cli
*
*   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *
*
* To remove this comment please upgrade your plan here: 
*      https://app.skaffolder.com/#!/upgrade
*
* Or get up to 70% discount sharing your unique link:
*       https://app.skaffolder.com/#!/register?friend=5dbfae239ef7a1181f8e04d2
*
* You will get 10% discount for each one of your friends
* 
*/
package com.khachsan.db.khachsan_db.service.base;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import javax.sql.DataSource;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.jdbc.core.BeanPropertyRowMapper;
import org.springframework.jdbc.core.namedparam.MapSqlParameterSource;
import org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate;
import org.springframework.jdbc.core.namedparam.SqlParameterSource;
import org.springframework.jdbc.core.simple.SimpleJdbcInsert;
import org.springframework.stereotype.Service;

import com.khachsan.db.khachsan_db.entity.Bill;
import com.khachsan.db.khachsan_db.service.BillService;

//IMPORT RELATIONS
import com.khachsan.db.khachsan_db.entity.Bill;
import com.khachsan.db.khachsan_db.entity.Bill;

@Service
public class BillBaseService {

	private static NamedParameterJdbcTemplate jdbcTemplate;
	
		@Autowired
	public void setDataSource(DataSource dataSource) {
		jdbcTemplate = new NamedParameterJdbcTemplate(dataSource);
	}
	


    //CRUD METHODS
    
    //CRUD - CREATE
    	
	public Bill insert(Bill obj) {
		Long id = jdbcTemplate.queryForObject("select max(_id) from `bill`", new MapSqlParameterSource(), Long.class);
		obj.set_id(id == null ? 1 : id + 1);
		String sql = "INSERT INTO `bill` (`_id`, `date`,`employessid`,`roomid`,`salarybill`) VALUES (:id,:date,:employessid,:roomid,:salarybill)";
			SqlParameterSource parameters = new MapSqlParameterSource()
		    .addValue("id", obj.get_id())
			.addValue("date", obj.getDate())
			.addValue("employessid", obj.getEmployessid())
			.addValue("roomid", obj.getRoomid())
			.addValue("salarybill", obj.getSalarybill());
		
		jdbcTemplate.update(sql, parameters);
		return obj;
	}
	
    	
    //CRUD - REMOVE
    
	public void delete(Long id) {
		String sql = "DELETE FROM `bill` WHERE `_id`=:id";
		SqlParameterSource parameters = new MapSqlParameterSource()
			.addValue("id", id);
		
		jdbcTemplate.update(sql, parameters);
	}

    	
    //CRUD - FIND BY Date
    	
	public List<Bill> findBydate(Long iddate) {
		
		String sql = "select * from `Bill` WHERE `date` = :iddate";
		
	    SqlParameterSource parameters = new MapSqlParameterSource()
		.addValue("iddate", iddate);
	    
	    return jdbcTemplate.query(sql, parameters, new BeanPropertyRowMapper(Bill.class));
	}
    	
    //CRUD - GET ONE
    	
	public Bill get(Long id) {
	    
		String sql = "select * from `bill` where `_id` = :id";
		
	    SqlParameterSource parameters = new MapSqlParameterSource()
			.addValue("id", id);
	    
	    return (Bill) jdbcTemplate.queryForObject(sql, parameters, new BeanPropertyRowMapper(Bill.class));
	}


    	
        	
    //CRUD - GET LIST
    	
	public List<Bill> getList() {
	    
		String sql = "select * from `bill`";
		
	    SqlParameterSource parameters = new MapSqlParameterSource();
	    return jdbcTemplate.query(sql, parameters, new BeanPropertyRowMapper(Bill.class));
	    
	    
	}

    	
    //CRUD - EDIT
    	
	public Bill update(Bill obj, Long id) {

		String sql = "UPDATE `bill` SET `date` = :date,`employessid` = :employessid,`roomid` = :roomid,`salarybill` = :salarybill  WHERE `_id`=:id";
		SqlParameterSource parameters = new MapSqlParameterSource()
			.addValue("id", id)
			.addValue("date", obj.getDate())
			.addValue("employessid", obj.getEmployessid())
			.addValue("roomid", obj.getRoomid())
			.addValue("salarybill", obj.getSalarybill());
		jdbcTemplate.update(sql, parameters);
	    return obj;
	}
	
    	
    
    
    
        
    

    
    /*
     * CUSTOM SERVICES
     * 
     *	These services will be overwritten and implemented in billService.java
     */
    

}
