/* 
* Generated by
* 
*      _____ _          __  __      _     _
*     / ____| |        / _|/ _|    | |   | |
*    | (___ | | ____ _| |_| |_ ___ | | __| | ___ _ __
*     \___ \| |/ / _` |  _|  _/ _ \| |/ _` |/ _ \ '__|
*     ____) |   < (_| | | | || (_) | | (_| |  __/ |
*    |_____/|_|\_\__,_|_| |_| \___/|_|\__,_|\___|_|
*
* The code generator that works in many programming languages
*
*			https://www.skaffolder.com
*
*
* You can generate the code from the command-line
*       https://npmjs.com/package/skaffolder-cli
*
*       npm install -g skaffodler-cli
*
*   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *
*
* To remove this comment please upgrade your plan here: 
*      https://app.skaffolder.com/#!/upgrade
*
* Or get up to 70% discount sharing your unique link:
*       https://app.skaffolder.com/#!/register?friend=5dbfae239ef7a1181f8e04d2
*
* You will get 10% discount for each one of your friends
* 
*/
package com.khachsan.db.khachsan_db.service.base;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import javax.sql.DataSource;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.jdbc.core.BeanPropertyRowMapper;
import org.springframework.jdbc.core.namedparam.MapSqlParameterSource;
import org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate;
import org.springframework.jdbc.core.namedparam.SqlParameterSource;
import org.springframework.jdbc.core.simple.SimpleJdbcInsert;
import org.springframework.stereotype.Service;

import com.khachsan.db.khachsan_db.entity.Employess;
import com.khachsan.db.khachsan_db.service.EmployessService;

//IMPORT RELATIONS
import com.khachsan.db.khachsan_db.entity.Room;
import com.khachsan.db.khachsan_db.entity.Bill;

@Service
public class EmployessBaseService {

	private static NamedParameterJdbcTemplate jdbcTemplate;
	
		@Autowired
	public void setDataSource(DataSource dataSource) {
		jdbcTemplate = new NamedParameterJdbcTemplate(dataSource);
	}
	


    //CRUD METHODS
    
    //CRUD - CREATE
    	
	public Employess insert(Employess obj) {
		Long id = jdbcTemplate.queryForObject("select max(_id) from `employess`", new MapSqlParameterSource(), Long.class);
		obj.set_id(id == null ? 1 : id + 1);
		String sql = "INSERT INTO `employess` (`_id`, `disc`,`gender`,`name`,`position`,`salary`,`employessid`,`employessid`) VALUES (:id,:disc,:gender,:name,:position,:salary, :employessid , :employessid )";
			SqlParameterSource parameters = new MapSqlParameterSource()
		    .addValue("id", obj.get_id())
			.addValue("disc", obj.getDisc())
			.addValue("gender", obj.getGender())
			.addValue("name", obj.getName())
			.addValue("position", obj.getPosition())
			.addValue("salary", obj.getSalary())
			.addValue("employessid", obj.getEmployessid())
			.addValue("employessid", obj.getEmployessid());
		
		jdbcTemplate.update(sql, parameters);
		return obj;
	}
	
    	
    //CRUD - REMOVE
    
	public void delete(Long id) {
		String sql = "DELETE FROM `employess` WHERE `_id`=:id";
		SqlParameterSource parameters = new MapSqlParameterSource()
			.addValue("id", id);
		
		jdbcTemplate.update(sql, parameters);
	}

    	
    //CRUD - FIND BY Name
    	
	public List<Employess> findByname(Long idname) {
		
		String sql = "select * from `Employess` WHERE `name` = :idname";
		
	    SqlParameterSource parameters = new MapSqlParameterSource()
		.addValue("idname", idname);
	    
	    return jdbcTemplate.query(sql, parameters, new BeanPropertyRowMapper(Employess.class));
	}
    	
    //CRUD - GET ONE
    	
	public Employess get(Long id) {
	    
		String sql = "select * from `employess` where `_id` = :id";
		
	    SqlParameterSource parameters = new MapSqlParameterSource()
			.addValue("id", id);
	    
	    return (Employess) jdbcTemplate.queryForObject(sql, parameters, new BeanPropertyRowMapper(Employess.class));
	}


    	
        	
    //CRUD - GET LIST
    	
	public List<Employess> getList() {
	    
		String sql = "select * from `employess`";
		
	    SqlParameterSource parameters = new MapSqlParameterSource();
	    return jdbcTemplate.query(sql, parameters, new BeanPropertyRowMapper(Employess.class));
	    
	    
	}

    	
    //CRUD - EDIT
    	
	public Employess update(Employess obj, Long id) {

		String sql = "UPDATE `employess` SET `disc` = :disc,`gender` = :gender,`name` = :name,`position` = :position,`salary` = :salary , `employessid` = :employessid , `employessid` = :employessid  WHERE `_id`=:id";
		SqlParameterSource parameters = new MapSqlParameterSource()
			.addValue("id", id)
			.addValue("disc", obj.getDisc())
			.addValue("gender", obj.getGender())
			.addValue("name", obj.getName())
			.addValue("position", obj.getPosition())
			.addValue("salary", obj.getSalary())
			.addValue("employessid", obj.getEmployessid())
			.addValue("employessid", obj.getEmployessid());
		jdbcTemplate.update(sql, parameters);
	    return obj;
	}
	
    	
    
    
    
        
    

    
    /*
     * CUSTOM SERVICES
     * 
     *	These services will be overwritten and implemented in employessService.java
     */
    

}
